#1、画出常见的平稳线性序列的谱密度函数，
#如AR(1),AR(2),MA(1),MA(2),ARMA(1,1)，观察其特点。
library(TSA)
#MA(1)
theta=.9
ARMAspec(model=list(ma=-theta))
#-0.9
win.graph(width=4.875,height=2.5,pointsize=8)
theta=-.9
ARMAspec(model=list(ma=-theta))
#MA(2)
theta1=1;theta2=-0.6
ARMAspec(model=list(ma=-c(theta1,theta2)))
#AR(1)
phi=0.9
ARMAspec(model=list(ar=phi))
#AR(2)
phi1=1.5
phi2=-0.75
ARMAspec(model=list(ar=c(phi1,phi2)))
#ARMA(1,1)
phi=0.5;theta=0.8
ARMAspec(model=list(ar=phi,ma=-theta))
#2、对于上一问题中每一个生成的序列，画出对应的周期图。
#同时讨论周期图与谱密度函数的相似程度与序列长度的关系。
#ma(1)
x<-rnorm(500)
ma1<-filter(x,filter=c(1,-0.9),method=c("convolution"),sides=1)
periodogram(ma1[2:500])

#用函数arima.sim
ma1<-arima.sim(n=500,list(ma=0.9))
periodogram(ma1)
#ma(2)
ma2<-arima.sim(n=500,list(ma=-c(1,-0.6)))
periodogram(ma2)
#ar(1)
ar1<-arima.sim(n=500,list(ar=0.9))
periodogram(ar1)
#ar(2)
ar2<-arima.sim(n=500,list(ar=c(1.5,-0.75)))
periodogram(ar2)

#3、对于AR(1)和MA(1)，讨论不同参数取值下谱密度函数的
#形状差别。特别的，对于AR(1)模型，观察参数在平稳域内外
#时谱密度函数形状的异同。
ARMAspec(model=list(ma=-.1))
ARMAspec(model=list(ma=-.3))
ARMAspec(model=list(ma=-.5))
ARMAspec(model=list(ma=-.7))
ARMAspec(model=list(ma=-.9))
#ar
ARMAspec(model=list(ar=.2))
ARMAspec(model=list(ar=.4))
ARMAspec(model=list(ar=.6))
ARMAspec(model=list(ar=.8))
#


#平稳域外
ARMAspec(model=list(ar=.9))
ARMAspec(model=list(ar=3))